# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js TESTNET CI

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Check Keys
      run: |
        echo "The API key is:${{ secrets.CARDANO_TESTNET }}"  
    - name: Create env file
      run: |
        touch .env
        echo CARDANO_NET_MAGIC=${{ secrets.CARDANO_TESTNET }} >> .env
        cat .env   
    - uses: actions/checkout@master
    - name: Copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: '185.193.66.140'
        username: 'admin'
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "."
        target: "/opt/cardano/cardano_plain_express"
        
    - name: Restart Service
      uses: appleboy/ssh-action@master
      with:
        host: '185.193.66.140'
        username: 'admin'
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd /opt/cardano/cardano_plain_express
          npm install
          pm2 restart app
        
       
   
