name: Node.js TESTNET CI

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

env:
  BLOKARIA_WEBSITE: "https://testnet.natureplant.com/"
  RECEIVER_ADDR: "addr_test1qzm6pmsn6wk55lzucqc3rls6evcwelz9a0v8p93sk6xu63unzny0fmcma635udm94yxl466juagdta0fkyvqerx8yd5sxcax9a"
  CARDANO_NET_MAGIC: "1"
  CARDANO_CLI_LOCAL_PATH: "/home/admin/.local/bin/cardano-cli"
  CARDANO_NODE_SOCKET_PATH: "/opt/cardano/cnode/sockets"
  SHELLEY_GENESIS_PATH: "/opt/cardano/cnode/files/conway-genesis.json"
  CARDANO_ERA: "conway"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Print ENV KEYS
        ## Reference your environment variables
        run: |
          echo "The API key is: $BLOKARIA_WEBSITE" 
          echo "Receiver Addr: $RECEIVER_ADDR"
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_CARDANO_NET_MAGIC: ${{ env.CARDANO_NET_MAGIC }}
          envkey_BLOKARIA_WEBSITE: ${{ env.BLOKARIA_WEBSITE }}
          envkey_RECEIVER_ADDR: ${{ env.RECEIVER_ADDR }}
          envkey_CARDANO_CLI_LOCAL_PATH: ${{ env.CARDANO_CLI_LOCAL_PATH }}
          envkey_CARDANO_NODE_SOCKET_PATH: ${{ env.CARDANO_NODE_SOCKET_PATH }}
          envkey_SHELLEY_GENESIS_PATH: ${{ env.SHELLEY_GENESIS_PATH }}
          envkey_CARDANO_ERA: ${{ env.CARDANO_ERA }}
          file_name: .env
      - name: Copy file .env via ssh password
        uses: appleboy/scp-action@master
        with:
          host: "185.193.66.140"
          username: "admin"
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: ".env"
          target: "/opt/cardano/cardano_plain_express"
      - uses: actions/checkout@master
      - name: Copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: "185.193.66.140"
          username: "admin"
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "."
          target: "/opt/cardano/cardano_plain_express"

      - name: Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: "185.193.66.140"
          username: "admin"
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /opt/cardano/cardano_plain_express
            npm install
            pm2 restart ecosystem.config.js
